/**
 * Bootstrap layout emit: LayoutPlan + netlist → Mode B YAML string.
 * Seeds x/y and face banks from spine (or any plan) PortGeom — no second placer.
 * See docs/LAYOUT.md §9.
 */

/**
 * @param {object} netlist classified netlist
 * @param {object} plan layout plan from spine-v1 / from-document
 * @param {{ comment?: string }} [opts]
 * @returns {string} YAML text
 */
function emitLayoutYaml(netlist, plan, opts = {}) {
  const page = plan.pages && plan.pages[0];
  if (!page) throw new Error('emit-layout: empty plan');

  const portById = new Map((page.ports || []).map((p) => [p.portId, p]));
  const dossiers = [];

  // Emit in table column order for stable, human-readable files.
  const ordered = [...netlist.components].sort((a, b) => a.columnIndex - b.columnIndex);

  for (const comp of ordered) {
    const box = (page.boxes || []).find((b) => b.componentId === comp.id);
    if (!box) {
      throw new Error(`emit-layout: no box for component ${comp.name}`);
    }

    const sides = { N: [], E: [], S: [], W: [] };
    const named = netlist.ports.filter(
      (p) => p.componentId === comp.id && p.kind === 'named' && p.label
    );

    const onFace = { N: [], E: [], S: [], W: [] };
    for (const p of named) {
      const g = portById.get(p.id);
      if (!g || !g.side) {
        throw new Error(
          `emit-layout: no PortGeom for ${comp.name}.${p.label}`
        );
      }
      const side = g.side;
      if (!onFace[side]) {
        throw new Error(
          `emit-layout: bad side ${side} for ${comp.name}.${p.label}`
        );
      }
      onFace[side].push({ label: p.label, x: g.x, y: g.y });
    }

    for (const face of ['N', 'E', 'S', 'W']) {
      const list = onFace[face];
      // N/S: left → right (x); E/W: top → bottom (y)
      if (face === 'N' || face === 'S') {
        list.sort((a, b) => a.x - b.x || a.y - b.y);
      } else {
        list.sort((a, b) => a.y - b.y || a.x - b.x);
      }
      sides[face] = list.map((e) => e.label);
    }

    dossiers.push({
      name: comp.name,
      x: box.x,
      y: box.y,
      sides,
    });
  }

  const header =
    opts.comment ||
    [
      '# Emitted layout sidecar (Mode B dossiers).',
      '# Generated by asciiWiring --emit-layout from current place policy.',
      '# Table remains electrical SoT. Edit x/y and face banks; re-render with --layout.',
      '#',
    ].join('\n');

  return header + '\n' + formatComponentsYaml(dossiers);
}

/** Hand-format Mode B YAML so keys N/E/S/W/y stay unquoted (YAML 1.1 / stylistic). */
function formatComponentsYaml(dossiers) {
  const lines = ['components:'];
  for (const d of dossiers) {
    lines.push(`  ${formatKey(d.name)}:`);
    lines.push(`    x: ${d.x}`);
    lines.push(`    y: ${d.y}`);
    lines.push('    sides:');
    for (const face of ['N', 'E', 'S', 'W']) {
      const pins = d.sides[face];
      if (!pins.length) {
        lines.push(`      ${face}: []`);
      } else {
        lines.push(`      ${face}: [${pins.map(formatScalar).join(', ')}]`);
      }
    }
    lines.push('');
  }
  // Trailing blank already; trim to single trailing newline
  while (lines.length && lines[lines.length - 1] === '') lines.pop();
  return lines.join('\n') + '\n';
}

function formatKey(name) {
  // Bare key if safe identifier-like (incl. Ω etc. when needs quotes)
  if (/^[A-Za-z_][A-Za-z0-9_.-]*$/.test(name)) return name;
  return JSON.stringify(name);
}

function formatScalar(s) {
  // Quote when flow/YAML-special
  if (s === '' || /[:#\[\]{},&*!|>'"%@`]/.test(s) || /^-/.test(s) || /\s/.test(s)) {
    return JSON.stringify(s);
  }
  // Bare YES/NO/y/n/on/off can be booleans in YAML 1.1 — quote NO-like relay labels
  if (/^(y|n|yes|no|true|false|on|off|null)$/i.test(s)) {
    return JSON.stringify(s);
  }
  return s;
}

module.exports = { emitLayoutYaml };
